server:
  port: 80
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
