server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 333
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
  mvc:
    servlet:
      load-on-startup: 1


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xuwenlin.springcloud.entities


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
      instance-id: payment8002
      prefer-ip-address: true
